name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run security scan (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "python:3.9"
        format: "table"

    - name: Build Docker image
      run: docker build -t devsecops-app .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag devsecops-app ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest
